language: python
python:
  - "2.7"
  - "3.4"
install:
    - pip install -r requirements.txt
    - pip install braintree coveralls mock mysqlclient
env:
  - TRAVIS_DB=True
addons:
  postgresql: "9.4"
script:
  - coverage run --source=hc manage.py test
after_success:
  coveralls
notifications:
  slack: andela:14SZ2ED9ChjdWi2X5ZI5LXeI
